/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Clases.ClsCandidato;
import Clases.ClsEleccion;
import Clases.ClsMensaje;
import Clases.ClsVotante;
import Controladores.CtlEleccion;
import Controladores.CtlVotante;
import java.util.LinkedList;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FrameVotar extends javax.swing.JFrame {

    CtlVotante controladorVotante;
    CtlEleccion controladorEleccion;
    LinkedList<ClsEleccion> listaElecciones;
    LinkedList<ClsCandidato> listaCandidatos;
    
    
    public FrameVotar() {
        initComponents();
        this.setLocationRelativeTo(this);
        this.setResizable(false);
        this.setFocusable(false);
        this.labelBienvenido.setVisible(false);
        this.labelEleccion.setVisible(false);
        this.labelCandidato.setVisible(false);
        this.comboElecciones.setVisible(false);
        this.comboCandidatos.setVisible(false);
        this.botonVotar.setVisible(false);
        this.controladorVotante = new CtlVotante();
        this.controladorEleccion = new CtlEleccion();
        this.listaElecciones = new LinkedList<>();
        this.listaCandidatos = new LinkedList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textDocumento = new javax.swing.JTextField();
        botonBuscar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelEleccion = new javax.swing.JLabel();
        comboElecciones = new javax.swing.JComboBox<>();
        labelCandidato = new javax.swing.JLabel();
        comboCandidatos = new javax.swing.JComboBox<>();
        botonVotar = new javax.swing.JButton();
        labelBienvenido = new javax.swing.JLabel();
        botonInicio2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Votación");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 15, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Documento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        textDocumento.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(textDocumento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 200, -1));

        botonBuscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonBuscar.setText("Buscar");
        botonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(botonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 180));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelEleccion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelEleccion.setText("Elección");
        jPanel2.add(labelEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        comboElecciones.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        comboElecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEleccionesActionPerformed(evt);
            }
        });
        jPanel2.add(comboElecciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 200, -1));

        labelCandidato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelCandidato.setText("Candidato");
        jPanel2.add(labelCandidato, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        comboCandidatos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel2.add(comboCandidatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 200, -1));

        botonVotar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonVotar.setText("Votar");
        botonVotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVotarActionPerformed(evt);
            }
        });
        jPanel2.add(botonVotar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 80, 30));

        labelBienvenido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        labelBienvenido.setText("Bienvenido");
        jPanel2.add(labelBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, -1, -1));

        botonInicio2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonInicio2.setText("Inicio");
        botonInicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicio2ActionPerformed(evt);
            }
        });
        jPanel2.add(botonInicio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 80, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 400, 190));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 380, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        String documento = this.textDocumento.getText();
        boolean votanteRegistrado = false;

        LinkedList<ClsVotante> listaVotantes = this.controladorVotante.ObtenerVotantes();
        for (ClsVotante votante : listaVotantes) {
            if (votante.getNumero_documento().equals(documento)) {
                votanteRegistrado = true;
                break;
            }
        }

        if (votanteRegistrado) {
            LinkedList<ClsEleccion> listaElecciones = this.controladorEleccion.ObtenerElecciones();
            
            for (ClsEleccion itemEleccion : listaElecciones) {
                this.comboElecciones.addItem(itemEleccion.getNombre());
            }
            
            this.labelBienvenido.setVisible(true);
            this.labelEleccion.setVisible(true);
            this.labelCandidato.setVisible(true);
            this.comboElecciones.setVisible(true);
            this.comboCandidatos.setVisible(true);
            this.botonVotar.setVisible(true);
        } else {
            this.labelBienvenido.setVisible(false);
            this.labelEleccion.setVisible(false);
            this.labelCandidato.setVisible(false);
            this.comboElecciones.setVisible(false);
            this.comboCandidatos.setVisible(false);
            this.botonVotar.setVisible(false);
            JOptionPane.showMessageDialog(null, "El votante no se encuentra registrado en el sistema, por ende no podrá votar");
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void botonVotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVotarActionPerformed
        int eleccionSeleccionada = this.comboElecciones.getSelectedIndex();
        int candidatoSeleccionado = this.comboCandidatos.getSelectedIndex();
        
        String idVotante = this.textDocumento.getText();
        String idCandidato = this.listaCandidatos.get(candidatoSeleccionado).getNumeroDocumento();
        int idEleccion = this.listaElecciones.get(eleccionSeleccionada).getIdEleccion();
        
        ClsMensaje respuesta = this.controladorVotante.Votar(idVotante, idCandidato, idEleccion);
        JOptionPane.showMessageDialog(rootPane, respuesta.getDescripcion());
        this.textDocumento.setText("");
        this.labelBienvenido.setVisible(false);
        this.labelEleccion.setVisible(false);
        this.labelCandidato.setVisible(false);
        this.comboElecciones.setVisible(false);
        this.comboCandidatos.setVisible(false);
        this.botonVotar.setVisible(false);
        this.comboElecciones.removeAllItems();
        this.comboCandidatos.removeAllItems();
    }//GEN-LAST:event_botonVotarActionPerformed

    private void comboEleccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEleccionesActionPerformed
        
        this.comboCandidatos.removeAllItems();
        int tipoEleccionSeleccionada =   this.comboElecciones.getSelectedIndex();
        listaElecciones = this.controladorEleccion.ObtenerElecciones();
         
        ClsEleccion eleccion = listaElecciones.get(tipoEleccionSeleccionada);
        //JOptionPane.showMessageDialog(null,"Id de la eleccion seleccionada es: " + eleccion.getIdEleccion());
        
        listaCandidatos = this.controladorEleccion.ObtenerCandidatosEleccion(String.valueOf(eleccion.getIdEleccion()));
        
        for (ClsCandidato candidato : listaCandidatos) {
            this.comboCandidatos.addItem(candidato.getNombre());
        }
        
    }//GEN-LAST:event_comboEleccionesActionPerformed

    private void botonInicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicio2ActionPerformed
        FrameMenu inicio = new FrameMenu();
        inicio.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_botonInicio2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameVotar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameVotar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBuscar;
    private javax.swing.JButton botonInicio2;
    private javax.swing.JButton botonVotar;
    private javax.swing.JComboBox<String> comboCandidatos;
    private javax.swing.JComboBox<String> comboElecciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBienvenido;
    private javax.swing.JLabel labelCandidato;
    private javax.swing.JLabel labelEleccion;
    private javax.swing.JTextField textDocumento;
    // End of variables declaration//GEN-END:variables
}
